---
title: "Untitled"
author: "Al Kovaleski"
date: "4/22/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(car)
library(ggplot2)
library(lsmeans)
library(RVAideMemoire)
library(deming)
library(rgr)
library(tls)
library(cowplot)
library(agricolae)


dat=read.csv("ELMethod.csv")
dat=read.csv("ELMethodOut3.csv")
tdat=read.csv("ELTemp.csv")
tdat=aggregate(ActualT~Collection+Temperature,tdat,mean)
colnames(tdat)=c("Date","Temperature","RealT")
dat=merge(dat,tdat, by=c("Date","Temperature"))


dat1=dat[,c(1,6,8,9,10)]
dat1=dat1[complete.cases(dat1),]

summary(dat1)


dat1=subset(dat, Date %in% "3/13/20")
summary(dat1)

dat1$wrong=0
dat1$wrong[dat1$Cond_freeze>1.3*dat1$Cond_N]=1

dat1=subset(dat1, wrong %in% 0)
# dat3=dat1
# 
# dat3$Cond_freeze=dat3$Cond_N
# dat3$RealT=-200
# dat1=rbind(dat1,dat3)
summary(dat1)


dat1$Cond_boiling[is.na(dat1$Cond_boiling)]=dat1$Cond_N[is.na(dat1$Cond_boiling)]/0.5758


dat1$Rt=dat1$Cond_freeze/dat1$Cond_N
dat1$Rt2=dat1$Cond_freeze/dat1$Cond_boiling

dat1=dat1[complete.cases(dat1),]


lm1=lm(dat1$Rt~dat1$Accession+as.factor(dat1$RealT))



library(car)
Anova(lm1)


plot(dat1$Rt,lm1$fitted.values, col=as.factor(dat1$RealT))
abline(0,1)


library(MASS)
stud.res=studres(lm1)
plot(lm1$fitted.values,stud.res)
abline(0,0)
abline(3,0)
plot(dat2$Ro,stud.res)
hist(stud.res,breaks=50)
library(car)
qqPlot(stud.res)


cooks.dist=cooks.distance(lm1)

plot(cooks.dist)



not_outlier = which(abs(stud.res) <= 4)



dat1=dat1[not_outlier,]






dat2=subset(dat1, RealT %in% 4)
dat2$Ro=dat2$Cond_freeze/dat2$Cond_N
dat2=aggregate(Ro~Accession,dat2,mean)
dat1=merge(dat1,dat2, by="Accession")

dat2=subset(dat1, RealT %in% 4)
dat2$Ro2=dat2$Cond_freeze/dat2$Cond_boiling
dat2=aggregate(Ro2~Accession,dat2,mean)
dat1=merge(dat1,dat2, by="Accession")





summary(dat1)



dat2=dat1
dat2=aggregate(Rt~Accession+RealT,dat2,mean)
dat2=aggregate(Rt~Accession,dat2,max)

colnames(dat2)=c("Accession","Rmax")


dat1=merge(dat1,dat2,by="Accession")





dat1$L=100*(dat1$Rt-dat1$Ro)/(dat1$Rmax-dat1$Ro)


plot(dat1$RealT,dat1$L)

hist(dat1$Rt[dat1$RealT==4], breaks=20)


dat1$posRT=-dat1$RealT
dat1$posRT=dat1$posRT+10


summary(dat1)





library(drc)

mod1=drm((dat1$L/100)~dat1$posRT,dat1$Species, fct=LL.2(), type="continuous" )

summary(mod1)

library(sandwich)

ED(mod1,50, interval="delta", type="relative", level=0.95)-10
ED(mod1,0.50, interval="delta", type="absolute", level=0.95)
EDcomp(mod1,c(50,50), type="relative", vcov.=sandwich, multcomp=T, plotit=T)

ED(mod1,20, interval="delta", type="relative", level=0.95)-10
EDcomp(mod1,c(20,20), type="relative", vcov.=sandwich, multcomp=T, plotit=T)

ED(mod1,80, interval="delta", type="relative", level=0.95)-10
EDcomp(mod1,c(80,80), type="relative", vcov.=sandwich, multcomp=T, plotit=T)




###### Boiling Rt ######

mod2=drm((dat1$Rt2)~dat1$posRT,dat1$Species, fct=LL.4(fixed=c(NA,NA,NA,NA)), upperl =c(0,0.3,0.8,40) , type="continuous" )
summary(mod2)



library(sandwich)

ED(mod2,50, interval="delta", type="relative", level=0.95)-10
ED(mod2,0.50, interval="delta", type="absolute", level=0.95)
EDcomp(mod2,c(50,50), type="relative", vcov.=sandwich, multcomp=T, plotit=T)



###### Nitrogen Rt ######


mod3=drm((dat1$Rt)~dat1$posRT,dat1$Species, fct=LL.4(fixed=c(NA,NA,NA,NA)), upperl =c(0,0.3,0.8,40) , type="continuous" )
summary(mod)



library(sandwich)

ED(mod3,50, interval="delta", type="relative", level=0.95)-10
ED(mod3,0.50, interval="delta", type="absolute", level=0.95)
EDcomp(mod3,c(50,50), type="relative", vcov.=sandwich, multcomp=T, plotit=T)




```




```{r}
library(agricolae)
library(car)
dat5=read.csv("ResultsbyAccession-L_boiling.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)


dat5=read.csv("ResultsbyAccession-L_Nitrogen.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)



dat5=read.csv("ResultsbyAccession-Rt_Nitrogen.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)


lm1<-lm(absfif~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)



dat5=read.csv("ResultsbyAccession-Rt_boiling.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)


dat5=read.csv("ResultsbyAccession-L_Nitrogen-Gompertz.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)


lm1<-lm(tmax~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

```







