---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(car)
library(ggplot2)
library(lsmeans)
library(RVAideMemoire)
library(deming)
library(rgr)
library(tls)
library(cowplot)
library(sandwich)
library(drc)
library(car)
library(MASS)
library(agricolae)
library(corrplot)
library(grid)
library(soilphysics)
library(lme4)

dat=read.csv("ELMethod.csv")
dat=read.csv("ELMethodOut3.csv")
tdat=read.csv("ELTemp.csv")
tdat=aggregate(ActualT~Collection+Temperature,tdat,mean)
colnames(tdat)=c("Date","Temperature","RealT")
dat=merge(dat,tdat, by=c("Date","Temperature"))
dat$Species=as.factor(dat$Species)
dat$Accession=as.factor(dat$Accession)
dat$Color=as.factor(dat$Color)


dat1=dat[,c(1,6,8,9,10)]
dat1=dat1[complete.cases(dat1),]

summary(dat1)

###############################################################################
#################                                             #################
#################           STANDARDIZED ON BOILING           #################
#################                                             #################
###############################################################################
# As in Kreyling et al. 2015


dat1=subset(dat, Date %in% "3/13/20")
summary(dat1)

dat1$wrong=0
dat1$wrong[dat1$Cond_freeze>1.3*dat1$Cond_N]=1

dat1=subset(dat1, wrong %in% 0)
# dat3=dat1
# 
# dat3$Cond_freeze=dat3$Cond_N
# dat3$RealT=-200
# dat1=rbind(dat1,dat3)
summary(dat1)


dat1$Cond_boiling[is.na(dat1$Cond_boiling)]=dat1$Cond_N[is.na(dat1$Cond_boiling)]/0.5758


dat1$Rt=dat1$Cond_freeze/dat1$Cond_boiling
dat1=dat1[complete.cases(dat1),]


lm1=lm(dat1$Rt~dat1$Accession+as.factor(dat1$RealT))


Anova(lm1)



stud.res=studres(lm1)
plot(lm1$fitted.values,stud.res)
abline(0,0)
abline(3,0)
plot(dat2$Ro,stud.res)
hist(stud.res,breaks=50)
qqPlot(stud.res)


cooks.dist=cooks.distance(lm1)

plot(cooks.dist)

not_outlier = which(abs(stud.res) <= 4) ### Removing extreme outliers ####

dat1=dat1[not_outlier,]


### This step transforms temperatures in all positives to be used in log function ###

dat1$posRT=-dat1$RealT
summary(dat1)
dat1$posRT=dat1$posRT+10 


### Logistic model per species ###

mod1=drm((dat1$Rt)~dat1$posRT,dat1$Species, fct=LL.4(fixed=c(NA,NA,NA,NA)), upperl =c(0,0.3,0.8,40) , type="continuous" )
summary(mod1)




ED(mod1,50, interval="delta", type="relative", level=0.95)-10 ### -10 here to bring temperatures to the right position ###

ED(mod1,0.50, interval="delta", type="absolute", level=0.95) ### none reach 50% without any standardization ###



#### This step will extract data used to analyze the method ####

dat4=NULL

for (i in levels(factor(dat1$Accession))) {
  
  subdat=subset(dat1, Accession %in% i)
  
  d=mean(tail(sort(subdat$Rt),9))
  
  mod2=drm((subdat$Rt)~subdat$posRT, fct=LL.4(fixed=c(NA,NA,NA,NA)), upperl =c(0,0.3,0.8,45), type="continuous" )
  
  print(summary(mod2))
  
  b=mod2$coefficients[1]
  c=mod2$coefficients[2]
  d=mod2$coefficients[3]
  e=mod2$coefficients[4]
  
  twenty=as.numeric(as.character(ED(mod2,20, interval="delta", type="relative", level=0.95)[1]))-10
  fifty=as.numeric(as.character(ED(mod2,50, interval="delta", type="relative", level=0.95)[1]))-10
  eighty=as.numeric(as.character(ED(mod2,80, interval="delta", type="relative", level=0.95)[1]))-10
  absfif=as.numeric(as.character(ED(mod2,0.50, interval="delta", type="absolute", level=0.95)[1]))-10

  
  dat4=rbind(dat4,c("Rt_boiling",i,levels(factor(subdat$Species)),b,c,d,e,twenty,fifty,eighty,absfif))
  
  
}

dat4=data.frame(dat4)
colnames(dat4)=c("Method","Accession","Species","b","c","d","e","twenty","fifty","eighty","absfif")

dat4$b=as.numeric(as.character(dat4$b))
dat4$c=as.numeric(as.character(dat4$c))
dat4$d=as.numeric(as.character(dat4$d))
dat4$e=as.numeric(as.character(dat4$e))
dat4$twenty=-as.numeric(as.character(dat4$twenty))
dat4$fifty=-as.numeric(as.character(dat4$fifty))
dat4$eighty=-as.numeric(as.character(dat4$eighty))
dat4$absfif=-as.numeric(as.character(dat4$absfif))


write.csv(dat4, "ResultsbyAccession-Rt_boiling.csv")


##### This part will create graphs for each Species separately #####

for (i in levels(dat1$Species)) {
  
  subdat=subset(dat1, Species %in% i)
  
  subdat4=subset(dat4, Accession %in% levels(factor(subdat$Accession)))
  
  mod1=drm((subdat$Rt)~subdat$posRT, fct=LL.4(fixed=c(NA,NA,NA,NA)),
           start=c(-7.3,0.3,0.6,30), upperl =c(0,0.3,0.9,40) , type="continuous" )
  
  
  subdat$pred=predict(mod1)
  print((cor(subdat$pred,subdat$Rt))^2)
  
  ### Step to create error lines for function ###
  
  (vc <- vcov(mod1))

  coef(summary(mod1))[, "Std. Error"]
  
  sqrt(diag(vc))
  
  require("MASS")
  set.seed(345)
  nsim <- 5000
  sim <- mvrnorm(nsim, mu = coef(mod1),  Sigma = vc)
  head(sim)
  
  take <- data.frame(sample(nrow(sim), 100)) ## take 25 simulations at random
  
  colnames(take)="take"
  
  dat.pred=NULL
  dat.pred$x=seq(0,95,1)
  dat.pred=data.frame(dat.pred)


    for (j in take$take){
      
    
      g=sim[j,1]
      n=sim[j,2]
      m=sim[j,3]
      h=sim[j,4]
      
      
      #print(paste(b, e, f, g, h,((g>0) | (b>0) | (f<0.11)) ))
      
    
      
      y =100*n+(100* (m-n))/(1+exp(g*(log(dat.pred$x)-log(h))))
      
      dat.pred=cbind(dat.pred,y)
    }


  colnames(dat.pred)=c("x", seq(1, ncol(dat.pred)-1,1))
  
  dat.pred=data.frame(dat.pred[1],stack(dat.pred[2:ncol(dat.pred)]))
  
  
  
  
  
  
  x=seq(0,95,1)
  
  pred=data.frame(x)
  
  for (j in levels(factor(subdat4$Accession))) {
    
    y=(subdat4$c[subdat4$Accession==j]*100)+(100*(subdat4$d[subdat4$Accession==j]-subdat4$c[subdat4$Accession==j]))/(1+exp(subdat4$b[subdat4$Accession==j]*(log(x)-log(subdat4$e[subdat4$Accession==j]))))
    
    pred=cbind(pred,y)
    
  }

  colnames(pred)=c("x",levels(factor(subdat4$Accession)))
  pred=data.frame(pred[1],stack(pred[2:ncol(pred)]))
  colnames(pred)=c("x","y","Accession")
  
  
  predL= (100*mod1$coefficients[2])+(100*(mod1$coefficients[3]-mod1$coefficients[2]))/(1+exp(mod1$coefficients[1]*(log(x)-log(mod1$coefficients[4]))))
  
  
    print(ggplot()+
         # geom_line(aes(x=-dat.pred$x+10, y=dat.pred$values, group=dat.pred$ind ), alpha=0.1, size=0.2)+
        geom_line(aes(x=-pred$x+10,y=pred$y, col=pred$Accession), lty=2, size=0.7)+
        geom_line(aes(x=-x+10, y=predL), size=1)+
        geom_point(aes(x=subdat$RealT, y=100*subdat$Rt, fill=subdat$Accession),
                   shape=21, position = position_dodge(width=2), size=2.5)+
          scale_y_continuous(limits=c(-10,110), breaks=c(0,25,50,75,100))+
          ylab("Electrolyte Leakage (% Nitrogen Leakage)") + xlab("Temperature (°C)") +
          labs(col="Accession",fill="Accession")+
          ggtitle(i)+
          theme_bw(base_size = 14)+
          theme(legend.position = c(0.77,0.81),
                legend.text.align= 1,
                legend.text = element_text(size=12),
                panel.grid.minor = element_blank(),
                legend.background = element_rect(fill="transparent"),
                legend.key = element_rect( fill = NA),
                panel.border = element_rect(size=1),
                axis.text=element_text(color="black"))
    
    )
}





###############################################################################
#################                                             #################
################# STANDARDIZED ON BOILING - Bringing 4C to 0  #################
#################                                             #################
###############################################################################
# As in Flint 1967

dat1=subset(dat, Date %in% "3/13/20")
summary(dat1)

dat1$wrong=0
dat1$wrong[dat1$Cond_freeze>1.3*dat1$Cond_N]=1

dat1=subset(dat1, wrong %in% 0)
summary(dat1)


dat1$Cond_boiling[is.na(dat1$Cond_boiling)]=dat1$Cond_N[is.na(dat1$Cond_boiling)]/0.5758


dat1$Rt=dat1$Cond_freeze/dat1$Cond_boiling
dat1=dat1[complete.cases(dat1),]


lm1=lm(dat1$Rt~dat1$Accession+as.factor(dat1$RealT))
Anova(lm1)


stud.res=studres(lm1)
plot(lm1$fitted.values,stud.res)
abline(0,0)
abline(c(4,-4),0)
plot(dat1$Rt,stud.res)
hist(stud.res,breaks=50)
qqPlot(stud.res)
cooks.dist=cooks.distance(lm1)
plot(cooks.dist)

not_outlier = which(abs(stud.res) <= 4)
dat1=dat1[not_outlier,]



##### Step to normalize based on 4C being 0% #####

dat2=subset(dat1, RealT %in% 4)
dat2$Ro=dat2$Cond_freeze/dat2$Cond_boiling
dat2=aggregate(Ro~Accession,dat2,mean)
dat1=merge(dat1,dat2, by="Accession")

summary(dat1)



dat1$L=100*(dat1$Rt-dat1$Ro)/(1-dat1$Ro)


#### Making positive temperatures ####

dat1$posRT=-dat1$RealT
dat1$posRT=dat1$posRT+10



library(drc)
mod1=drm((dat1$L)~dat1$posRT,dat1$Species, fct=LL.4(fixed=c(NA,0,NA,NA)), upperl =c(0,90,40) , type="continuous" )
summary(mod1)



library(sandwich)

ED(mod1,50, interval="delta", type="relative", level=0.95)-10
ED(mod1,50, interval="delta", type="absolute", level=0.95)-10 #### Still none reach 50% ####


dat4=NULL

for (i in levels(factor(dat1$Accession))) {
  
  subdat=subset(dat1, Accession %in% i)
  
  d=mean(tail(sort(subdat$Rt),9))
  
  mod2=drm((subdat$L)~subdat$posRT, fct=LL.4(fixed=c(NA,0,NA,NA)), upperl =c(0,90,45), type="continuous" )
  
  print(summary(mod2))
  
  b=mod2$coefficients[1]
  d=mod2$coefficients[2]
  e=mod2$coefficients[3]
  
  twenty=as.numeric(as.character(ED(mod2,20, interval="delta", type="relative", level=0.95)[1]))-10
  fifty=as.numeric(as.character(ED(mod2,50, interval="delta", type="relative", level=0.95)[1]))-10
  eighty=as.numeric(as.character(ED(mod2,80, interval="delta", type="relative", level=0.95)[1]))-10
  
  dat4=rbind(dat4,c("Rt_Boiling_zeroed",i,levels(factor(subdat$Species)),b,d,e,twenty,fifty,eighty))
  
  
}

dat4=data.frame(dat4)
colnames(dat4)=c("Method","Accession","Species","b","d","e","twenty","fifty","eighty")

dat4$b=as.numeric(as.character(dat4$b))
dat4$d=as.numeric(as.character(dat4$d))
dat4$e=as.numeric(as.character(dat4$e))
dat4$twenty=-as.numeric(as.character(dat4$twenty))
dat4$fifty=-as.numeric(as.character(dat4$fifty))
dat4$eighty=-as.numeric(as.character(dat4$eighty))


write.csv(dat4, "ResultsbyAccession-Rt_Boiling_zeroed.csv")



for (i in levels(dat1$Species)) {
  
  subdat=subset(dat1, Species %in% i)
  
  subdat4=subset(dat4, Accession %in% levels(factor(subdat$Accession)))
  
  mod1=drm((subdat$L)~subdat$posRT, fct=LL.4(fixed=c(NA,0,NA,NA)), start=c(-7.3,45,30), upperl =c(0,50,40) , type="continuous" )
  
  subdat$pred=predict(mod1)
  print((cor(subdat$pred,subdat$L))^2)
  
  (vc <- vcov(mod1))

coef(summary(mod1))[, "Std. Error"]

sqrt(diag(vc))

require("MASS")
set.seed(345)
nsim <- 5000
sim <- mvrnorm(nsim, mu = coef(mod1),  Sigma = vc)
head(sim)

take <- data.frame(sample(nrow(sim), 100)) ## take 25 simulations at random

colnames(take)="take"

dat.pred=NULL
dat.pred$x=seq(0,95,1)
dat.pred=data.frame(dat.pred)


for (j in take$take){
  

  g=sim[j,1]
  m=sim[j,2]
  h=sim[j,3]
  
  
  #print(paste(b, e, f, g, h,((g>0) | (b>0) | (f<0.11)) ))
  

  
  y =(m)/(1+exp(g*(log(dat.pred$x)-log(h))))
  
  dat.pred=cbind(dat.pred,y)
}


colnames(dat.pred)=c("x", seq(1, ncol(dat.pred)-1,1))

dat.pred=data.frame(dat.pred[1],stack(dat.pred[2:ncol(dat.pred)]))
  
  
  
  
  
  
  x=seq(0,95,1)
  
  pred=data.frame(x)
  
  for (j in levels(factor(subdat4$Accession))) {
    
    y=(subdat4$d[subdat4$Accession==j])/(1+exp(subdat4$b[subdat4$Accession==j]*(log(x)-log(subdat4$e[subdat4$Accession==j]))))
    
    pred=cbind(pred,y)
    
  }

  colnames(pred)=c("x",levels(factor(subdat4$Accession)))
  pred=data.frame(pred[1],stack(pred[2:ncol(pred)]))
  colnames(pred)=c("x","y","Accession")
  
  
  predL= (mod1$coefficients[2])/(1+exp(mod1$coefficients[1]*(log(x)-log(mod1$coefficients[3]))))
  
  
    print(ggplot()+
          #geom_line(aes(x=-dat.pred$x+10, y=dat.pred$values, group=dat.pred$ind ), alpha=0.1, size=0.2)+
        geom_line(aes(x=-pred$x+10,y=pred$y, col=pred$Accession), lty=2, size=0.7)+
        geom_line(aes(x=-x+10, y=predL), size=1)+
        geom_point(aes(x=subdat$RealT, y=subdat$L, fill=subdat$Accession), shape=21, position = position_dodge(width=2), size=2.5)+
          scale_y_continuous(limits=c(-10,110), breaks=c(0,25,50,75,100))+
          ylab("Electrolyte Leakage (% Nitrogen Leakage)") + xlab("Temperature (°C)") +
          labs(col="Accession",fill="Accession")+
          ggtitle(i)+
          theme_bw(base_size = 14)+
          theme(legend.position = c(0.77,0.81),
                legend.text.align= 1,
                legend.text = element_text(size=12),
                panel.grid.minor = element_blank(),
                legend.background = element_rect(fill="transparent"),
                legend.key = element_rect( fill = NA),
                panel.border = element_rect(size=1),
                axis.text=element_text(color="black"))
    
    )
}





###############################################################################
#################                                             #################
#################    Relative 0-100 STANDARDIZED ON BOILING   #################
#################                                             #################
###############################################################################
# Similar to Lim et al 1998

dat1=subset(dat, Date %in% "3/13/20")
summary(dat1)

dat1$wrong=0
dat1$wrong[dat1$Cond_freeze>1.3*dat1$Cond_N]=1

dat1=subset(dat1, wrong %in% 0)
summary(dat1)


dat1$Cond_boiling[is.na(dat1$Cond_boiling)]=dat1$Cond_N[is.na(dat1$Cond_boiling)]/0.5758


dat1$Rt=dat1$Cond_freeze/dat1$Cond_boiling
dat1=dat1[complete.cases(dat1),]


lm1=lm(dat1$Rt~dat1$Accession+as.factor(dat1$RealT))
Anova(lm1)


stud.res=studres(lm1)
plot(lm1$fitted.values,stud.res)
abline(0,0)
abline(3,0)
plot(dat2$Ro,stud.res)
hist(stud.res,breaks=50)
qqPlot(stud.res)
cooks.dist=cooks.distance(lm1)
plot(cooks.dist)



not_outlier = which(abs(stud.res) <= 4)
dat1=dat1[not_outlier,]



#### Step to normalize 4C as 0 ####

dat2=subset(dat1, RealT %in% 4)
dat2$Ro=dat2$Cond_freeze/dat2$Cond_boiling
dat2=aggregate(Ro~Accession,dat2,mean)
dat1=merge(dat1,dat2, by="Accession")


#### Step to take maximum average leakage ####

dat2=dat1
dat2=aggregate(Rt~Accession+RealT,dat2,mean)
dat2=aggregate(Rt~Accession,dat2,max)
colnames(dat2)=c("Accession","Rmax")
dat1=merge(dat1,dat2,by="Accession")

#### Normalizing from 0 to 100 ####

dat1$L=100*(dat1$Rt-dat1$Ro)/(dat1$Rmax-dat1$Ro)



#### Create positive-only temperatures ####

dat1$posRT=-dat1$RealT
dat1$posRT=dat1$posRT+10



library(drc)
mod1=drm((dat1$L/100)~dat1$posRT,dat1$Species, fct=LL.2() , type="continuous" )
summary(mod1)



library(sandwich)

ED(mod1,50, interval="delta", type="relative", level=0.95)-10

ED(mod1,0.50, interval="delta", type="absolute", level=0.95)-10 ### Absolute and relative are the same now ####



#### Extracting estimates for comparisons ####

dat4=NULL

for (i in levels(factor(dat1$Accession))) {
  
  subdat=subset(dat1, Accession %in% i)
  mod2=drm((subdat$L/100)~subdat$posRT, fct=LL.2(),  type="continuous" )
  
  print(summary(mod2))
  
  b=mod2$coefficients[1]
  e=mod2$coefficients[2]
  
    
  twenty=as.numeric(as.character(ED(mod2,20, interval="delta", type="relative", level=0.95)[1]))-10
  fifty=as.numeric(as.character(ED(mod2,50, interval="delta", type="relative", level=0.95)[1]))-10
  eighty=as.numeric(as.character(ED(mod2,80, interval="delta", type="relative", level=0.95)[1]))-10

  
  dat4=rbind(dat4,c("L_boiling",i,levels(factor(subdat$Species)),b,e,twenty,fifty,eighty))
  
  
}

dat4=data.frame(dat4)
colnames(dat4)=c("Method","Accession","Species","b","e","twenty","fifty","eighty")

dat4$b=as.numeric(as.character(dat4$b))
dat4$e=as.numeric(as.character(dat4$e))
dat4$twenty=-as.numeric(as.character(dat4$twenty))
dat4$fifty=-as.numeric(as.character(dat4$fifty))
dat4$eighty=-as.numeric(as.character(dat4$eighty))


write.csv(dat4, "ResultsbyAccession-L_boiling.csv")


#### Creates graphs for each Species ####

for (i in levels(dat1$Species)) {
  
  subdat=subset(dat1, Species %in% i)
  
  subdat4=subset(dat4, Accession %in% levels(factor(subdat$Accession)))
  
  mod1=drm((subdat$L/100)~subdat$posRT, fct=LL.2(),  type="continuous" )
  
  subdat$pred=100*predict(mod1)
  print((cor(subdat$pred,subdat$Rt))^2)
  
  (vc <- vcov(mod1))

  coef(summary(mod1))[, "Std. Error"]
  
  sqrt(diag(vc))
  
  require("MASS")
  set.seed(10)
  nsim <- 5000
  sim <- mvrnorm(nsim, mu = coef(mod1),  Sigma = vc)
  head(sim)
  
  take <- data.frame(sample(nrow(sim), 100)) ## take 25 simulations at random
  
  colnames(take)="take"
  
  dat.pred=NULL
  dat.pred$x=seq(0,95,1)
  dat.pred=data.frame(dat.pred)
  
  
  for (j in take$take){
    
  
    g=sim[j,1]
    h=sim[j,2]
    
    
    #print(paste(b, e, f, g, h,((g>0) | (b>0) | (f<0.11)) ))
    
  
    
    y =(100)/(1+exp(g*(log(dat.pred$x)-log(h))))
    
    dat.pred=cbind(dat.pred,y)
  }
  
  
  colnames(dat.pred)=c("x", seq(1, ncol(dat.pred)-1,1))
  
  dat.pred=data.frame(dat.pred[1],stack(dat.pred[2:ncol(dat.pred)]))
    
    
    
    
    
    
  x=seq(0,95,1)
  
  pred=data.frame(x)
  
  for (j in levels(factor(subdat4$Accession))) {
    
    y=(100)/(1+exp(subdat4$b[subdat4$Accession==j]*(log(x)-log(subdat4$e[subdat4$Accession==j]))))
    
    pred=cbind(pred,y)
    
  }

  colnames(pred)=c("x",levels(factor(subdat4$Accession)))
  pred=data.frame(pred[1],stack(pred[2:ncol(pred)]))
  colnames(pred)=c("x","y","Accession")
  
  
  predL= (100)/(1+exp(mod1$coefficients[1]*(log(x)-log(mod1$coefficients[2]))))
  
  
  subdat2=data.frame(aggregate(L~Accession+RealT,subdat,mean))
  subdat3=data.frame(aggregate(L~Accession+RealT,subdat,sd))
  

  
    print(ggplot()+
          #geom_line(aes(x=-dat.pred$x+10, y=dat.pred$values, group=dat.pred$ind ), alpha=0.1, size=0.2)+
        geom_line(aes(x=-pred$x+10,y=pred$y, col=pred$Accession), lty=2, size=0.7)+
        geom_line(aes(x=-x+10, y=predL), size=1)+
         geom_point(aes(x=subdat$RealT, y=subdat$L, fill=subdat$Accession), shape=21, position = position_dodge(width=2), size=2.5)+
          scale_y_continuous(limits=c(-30,140), breaks=c(0,25,50,75,100))+
          ylab("Electrolyte Leakage (%)") + xlab("Temperature (°C)") +
          labs(col="Accession",fill="Accession")+
          ggtitle(i)+
          theme_bw(base_size = 14)+
          theme(legend.position = c(0.77,0.81),
                legend.text.align= 0,
                legend.text = element_text(size=12),
                panel.grid.minor = element_blank(),
                legend.background = element_rect(fill="transparent"),
                legend.key = element_rect( fill = NA),
                panel.border = element_rect(size=1),
                axis.text=element_text(color="black"))
    
    )
  
}


###############################################################################
#################                                             #################
#################    Relative 0-100 STANDARDIZED ON BOILING   #################
#################                  GOMPERTZ                   #################
###############################################################################

dat1=subset(dat, Date %in% "3/13/20")
summary(dat1)

dat1$wrong=0
dat1$wrong[dat1$Cond_freeze>1.3*dat1$Cond_N]=1

dat1=subset(dat1, wrong %in% 0)
summary(dat1)


dat1$Cond_boiling[is.na(dat1$Cond_boiling)]=dat1$Cond_N[is.na(dat1$Cond_boiling)]/0.5758


dat1$Rt=dat1$Cond_freeze/dat1$Cond_boiling
dat1=dat1[complete.cases(dat1),]


lm1=lm(dat1$Rt~dat1$Accession+as.factor(dat1$RealT))
Anova(lm1)


stud.res=studres(lm1)
plot(lm1$fitted.values,stud.res)
abline(0,0)
abline(3,0)
plot(dat2$Ro,stud.res)
hist(stud.res,breaks=50)
qqPlot(stud.res)
cooks.dist=cooks.distance(lm1)
plot(cooks.dist)



not_outlier = which(abs(stud.res) <= 4)
dat1=dat1[not_outlier,]



#### Step to normalize 4C as 0 ####

dat2=subset(dat1, RealT %in% 4)
dat2$Ro=dat2$Cond_freeze/dat2$Cond_boiling
dat2=aggregate(Ro~Accession,dat2,mean)
dat1=merge(dat1,dat2, by="Accession")


#### Step to take maximum average leakage ####

dat2=dat1
dat2=aggregate(Rt~Accession+RealT,dat2,mean)
dat2=aggregate(Rt~Accession,dat2,max)
colnames(dat2)=c("Accession","Rmax")
dat1=merge(dat1,dat2,by="Accession")

#### Normalizing from 0 to 100 ####

dat1$L=100*(dat1$Rt-dat1$Ro)/(dat1$Rmax-dat1$Ro)



#### Create positive-only temperatures ####

dat1$posRT=-dat1$RealT
dat1$posRT=dat1$posRT+10



#### Extract parameters based on Gompertz ####

dat4=NULL

for (i in levels(factor(dat1$Accession))) {
  
  subdat=subset(dat1, Accession %in% i)

  
  vini.lm4= nls(L~100*exp(-b*exp(-k*posRT))
              
              , data=subdat, start=list(b=3,k=0.05),upper = list(b=100,k=0.3), algorithm="port",trace=F)
  
  
  print(summary(vini.lm4))
  
  r2=as.numeric(Rsq(vini.lm4)[2])
  
  b=summary(vini.lm4)$coefficients[1]
  k=summary(vini.lm4)$coefficients[2]
  
 
  twenty=-log(log(5)/b)/k-10
  fifty=-log(log(2)/b)/k-10
  eighty=-log(log(1.25)/b)/k-10
  
  tmax=-log(1/(b))/k-10


  
  dat4=rbind(dat4,c("L_Boiling_Gomp",i,levels(factor(subdat$Species)),b,k,twenty,fifty,eighty, tmax,r2))
  
  
}

dat4=data.frame(dat4)
colnames(dat4)=c("Method","Accession","Species","b","k","twenty","fifty","eighty","tmax","R2")

dat4$b=as.numeric(as.character(dat4$b))
dat4$k=as.numeric(as.character(dat4$k))
dat4$twenty=-as.numeric(as.character(dat4$twenty))
dat4$fifty=-as.numeric(as.character(dat4$fifty))
dat4$eighty=-as.numeric(as.character(dat4$eighty))
dat4$tmax=-as.numeric(as.character(dat4$tmax))
dat4$R2=as.numeric(as.character(dat4$R2))

write.csv(dat4, "ResultsbyAccession-L_Boiling-Gompertz.csv")


##### Makes graphs for each Species #####

for (i in levels(dat1$Species)) {
  
  subdat=subset(dat1, Species %in% i)
  
  subdat4=subset(dat4, Accession %in% levels(factor(subdat$Accession)))
  
  mod1= nls(L~100*exp(-b*exp(-k*posRT))
              
              , data=subdat, start=list(b=3,k=0.05),upper = list(b=100,k=0.3), algorithm="port",trace=F)
  
  print(i)
  print(summary(mod1))
  print(Rsq(mod1))
  
  (vc <- vcov(mod1))

coef(summary(mod1))[, "Std. Error"]

sqrt(diag(vc))

require("MASS")
set.seed(10)
nsim <- 5000
sim <- mvrnorm(nsim, mu = coef(mod1),  Sigma = vc)
head(sim)

take <- data.frame(sample(nrow(sim), 100)) ## take 25 simulations at random

colnames(take)="take"

dat.pred=NULL
dat.pred$x=seq(0,95,1)
dat.pred=data.frame(dat.pred)


for (j in take$take){
  

  g=sim[j,1]
  h=sim[j,2]
  
  
  #print(paste(b, e, f, g, h,((g>0) | (b>0) | (f<0.11)) ))
  

  
  y =100*exp(-g*exp(-h*dat.pred$x))
  
  dat.pred=cbind(dat.pred,y)
}


colnames(dat.pred)=c("x", seq(1, ncol(dat.pred)-1,1))

dat.pred=data.frame(dat.pred[1],stack(dat.pred[2:ncol(dat.pred)]))
  
  
  
  
  
  
  x=seq(0,95,1)
  
  pred=data.frame(x)
  
  for (j in levels(factor(subdat4$Accession))) {
    
    y=100*exp(-subdat4$b[subdat4$Accession==j]*exp(-subdat4$k[subdat4$Accession==j]*x))
    
    pred=cbind(pred,y)
    
  }

  colnames(pred)=c("x",levels(factor(subdat4$Accession)))
  pred=data.frame(pred[1],stack(pred[2:ncol(pred)]))
  colnames(pred)=c("x","y","Accession")
  
  
  predL= 100*exp(-summary(mod1)$coefficients[1]*exp(-summary(mod1)$coefficients[2]*x))
    
  
  
  subdat2=data.frame(aggregate(L~Accession+RealT,subdat,mean))
  subdat3=data.frame(aggregate(L~Accession+RealT,subdat,sd))
  

  
    print(ggplot()+
          #geom_line(aes(x=-dat.pred$x+10, y=dat.pred$values, group=dat.pred$ind ), alpha=0.1, size=0.2)+
        geom_line(aes(x=-pred$x+10,y=pred$y, col=pred$Accession), lty=2, size=0.7)+
        geom_line(aes(x=-x+10, y=predL), size=1)+
        geom_point(aes(x=subdat$RealT, y=subdat$L, fill=subdat$Accession), shape=21, position = position_dodge(width=1), size=2.5)+
          scale_y_continuous(limits=c(-30,140), breaks=c(0,25,50,75,100))+
          ylab("Electrolyte Leakage (%)") + xlab("Temperature (°C)") +
          labs(col="Accession",fill="Accession")+
          ggtitle(i)+
          theme_bw(base_size = 14)+
          theme(legend.position = c(0.8,0.8),
                legend.text.align= 0,
                legend.text = element_text(size=12),
                panel.grid.minor = element_blank(),
                legend.background = element_rect(fill="transparent"),
                legend.key = element_rect( fill = NA),
                panel.border = element_rect(size=1),
                axis.text=element_text(color="black"))
    
    )
  
}



###############################################################################
#################                                             #################
#################          Comparing the 4 methods            #################
#################                                             #################
###############################################################################



dat5=read.csv("ResultsbyAccession-Rt_boiling.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(d~Species,data=dat5);Anova(lm1) ### height of the curve - no indication of correlation with phenology ###
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(d~Species,data=dat5);Anova(lm1) ### bottom of the curve - no indication of correlation with phenology ###
HSD.test(lm1,"Species",console=T,alpha=0.05)




dat5=read.csv("ResultsbyAccession-Rt_Boiling_zeroed.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)




dat5=read.csv("ResultsbyAccession-L_boiling.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)




dat5=read.csv("ResultsbyAccession-L_Boiling-Gompertz.csv")


lm1<-lm(twenty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(tmax~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)





###############################################################################
###############################################################################
################# STEM DAMAGE --- STEM DAMAGE --- STEM DAMAGE #################
#################                                             #################
#################          Estimating Stem Damage             #################
#################                                             #################
################# STEM DAMAGE --- STEM DAMAGE --- STEM DAMAGE #################
###############################################################################
###############################################################################



dat=read.csv("MapleStemDamage200324.csv")
dat$Species=as.factor(dat$Species)
dat$Genotype=as.factor(dat$Genotype)


cl.dat=read.csv("SpeciesGenos.csv")
cl.dat$Species=as.factor(cl.dat$Species)
cl.dat$Genotype=as.factor(cl.dat$Genotype)

dat$posT=-dat$Temperature+10

mod1=drm(dat$Damage~dat$posT, dat$Genotype,fct=LL.2(), type="continuous"   )

summary(mod1)

# for (i in levels(dat$Species)) {
#   
#   subdat=subset(dat, Species %in% i)
#   mod2=drm(subdat$Damage~subdat$posT, fct=LL.2(), type="continuous" )
#   print(i)
#   print(summary(mod2))
#   subdat$pred=predict(mod2)
#   print((cor(subdat$pred,subdat$Damage))^2 )
#   
# }


dat2=data.frame(ED(mod1,50, interval="delta", type="relative", level=0.95)[,1])-10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("fifty","Genotype")
dat2$Genotype=as.factor(gsub(':50','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat2,cl.dat)


dat2=data.frame(ED(mod1,20, interval="delta", type="relative", level=0.95)[,1])-10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("twenty","Genotype")
dat2$Genotype=as.factor(gsub(':20','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)

dat2=data.frame(ED(mod1,80, interval="delta", type="relative", level=0.95)[,1])-10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("eighty","Genotype")
dat2$Genotype=as.factor(gsub(':80','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)




lm1<-lm(twenty~Species,data=dat3);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(fifty~Species,data=dat3);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)

lm1<-lm(eighty~Species,data=dat3);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)


#### Using the LST method ####

dat4=data.frame(aggregate(Damage~Genotype+Species+Temperature, dat, min))
dat4=dat4[dat4$Damage<0.75,]
dat5=data.frame(aggregate(Temperature~Genotype+Species, dat4, min))

lm1<-lm(Temperature~Species,data=dat5);Anova(lm1)
HSD.test(lm1,"Species",console=T,alpha=0.05)


#### This analyzes all data together, at species level and makes comparison ####
mod2=drm(dat$Damage~dat$posT, dat$Species,fct=LL.2(), type="continuous"   )
EDcomp(mod2,c(50,50),type="relative",  multcomp=T, plotit=T)
ED(mod2,50, interval="delta", type="relative", level=0.95)-10




###############################################################################
#################                                             #################
#################       Comparing EL and Stem Damage          #################
#################                                             #################
###############################################################################




dat6=read.csv("ResultsbyAccession-L_boiling.csv")
dat6=dat6[,c(3,4,7,8,9)]
colnames(dat6)=c("Genotype","Species","Lim_20","Lim_50","Lim_80")

dat7=read.csv("ResultsbyAccession-Rt_Boiling_zeroed.csv")
dat7=dat7[,c(3,4,8,9,10)]
colnames(dat7)=c("Genotype","Species","Flint_20","Flint_50","Flint_80")

dat8=read.csv("ResultsbyAccession-Rt_boiling.csv")
dat8=dat8[,c(3,4,9,10,11)]
colnames(dat8)=c("Genotype","Species","Kreyling_20","Kreyling_50","Kreyling_80")

dat3a=dat3[,c(1,3,2,4,5)]
colnames(dat3a)=c("Genotype","Species","Damage_50","Damage_20","Damage_80")
dat3a[,3]=-dat3a[,3]
dat3a[,4]=-dat3a[,4]
dat3a[,5]=-dat3a[,5]


dat6g=read.csv("ResultsbyAccession-L_Nitrogen-Gompertz.csv")
dat6g=dat6g[,c(3,4,7,8,9,10)]
colnames(dat6g)=c("Genotype","Species","Gomp_20","Gomp_50","Gomp_80","Gomp_Tmax")


dat5a=dat5
colnames(dat5a)=c("Genotype","Species","Min_Dam")

dat9=merge(dat6,dat7)
dat9=merge(dat9,dat8)
dat9=merge(dat9,dat3a, all=T)
dat9=merge(dat9,dat5a)
dat9=merge(dat9,dat6g)
dat9$Genotype=as.factor(dat9$Genotype)
dat9$Species=as.factor(dat9$Species)

res=cor(dat9[c(3:11,16,17,18,19)],dat9[c(13,12,14,15)])



corrplot(res, method="pie",cl.lim=c(0,1), is.corr=FALSE,
         tl.col = "black", tl.srt = 45)


res=cor(dat9[c(3:5,19)],dat9[c(16:19)])



library(corrplot)
corrplot(res, method="pie",cl.lim=c(0,1), is.corr=FALSE,
         tl.col = "black", tl.srt = 45)


dat10=aggregate(.~Species,dat9,mean)


res=cor(dat10[c(3:11,16,17,18,19)],dat10[c(13,12,14,15)])


library(corrplot)
corrplot(res, method="pie",cl.lim=c(0,1), is.corr=FALSE,
         tl.col = "black", tl.srt = 45)




dat11=NULL

for (i in levels(factor(dat$Genotype))) {
  
  subdat=subset(dat, Genotype %in% i)
  mod2=drm(subdat$Damage~subdat$posT, fct=LL.2(),  type="continuous" )
  
  print(summary(mod2))
  
  b=mod2$coefficients[1]
  e=mod2$coefficients[2]

  
  dat11=rbind(dat11,c(i,levels(factor(subdat$Species)),b,e))
  
  
}

dat11=data.frame(dat11)
colnames(dat11)=c("Accession","Species","bDam","eDam")
dat11$bDam=as.numeric(as.character(dat11$bDam))
dat11$eDam=as.numeric(as.character(dat11$eDam))


dat6=read.csv("ResultsbyAccession-L_boiling.csv")
dat12=dat6[c(3,4,5,6)]
colnames(dat12)=c("Accession","Species","bL","eL")


dat13=merge(dat11,dat12)


x=seq(0,95,1)
  
pred=data.frame(x)
pred2=pred
  
for (j in levels(factor(dat13$Accession))) {
    
  y=(100)/(1+exp(dat13$bL[dat13$Accession==j]*(log(x)-log(dat13$eL[dat13$Accession==j]))))
  y2=(100)/(1+exp(dat13$bDam[dat13$Accession==j]*(log(x)-log(dat13$eDam[dat13$Accession==j]))))
  
  pred=cbind(pred,y)
  pred2=cbind(pred2,y2)
    
}

colnames(pred)=c("x",levels(factor(dat13$Accession)))
pred=data.frame(pred[1],stack(pred[2:ncol(pred)]))
colnames(pred)=c("x","y","Accession")

colnames(pred2)=c("x",levels(factor(dat13$Accession)))
pred2=data.frame(pred2[1],stack(pred2[2:ncol(pred2)]))
colnames(pred2)=c("x","y2","Accession")

pred3=merge(pred,pred2)


pred5=NULL

for (j in levels(pred3$Accession)) {
  
  pred4=subset(pred3, Accession %in% j)
  
  for (i in seq(1,99,1) ) {
    
    newx=pred4$x[abs(pred4$y-i)==min(abs(pred4$y-i)) ]
    newx2=pred4$x[abs(pred4$y2-i)==min(abs(pred4$y2-i)) ]
    
    pred5=rbind(pred5, c(j,i,newx,newx2))
    
  }
  
}

pred5=data.frame(pred5)

colnames(pred5)=c("Accession","Temperature","ELy","Damy")
pred5[,2]=as.numeric(as.character(pred5[,2]))
pred5[,3]=as.numeric(as.character(pred5[,3]))
pred5[,4]=as.numeric(as.character(pred5[,4]))

pred5$EL50=0

for (j in levels(pred5$Accession)) {
  
  pred5$EL50[pred5$Accession==j]=dat12$eL[dat12$Accession==j]
  
}


pred5$dif=(pred5$ELy-pred5$Damy)

ggplot()+
  geom_col(aes(x=pred5$Temperature,y=abs(pred5$dif), group=pred5$Accession),stat="identity",position = "identity", fill="gray30", alpha=0.1)+
  geom_smooth(aes(x=pred5$Temperature, y=abs(pred5$dif)), method="loess", span=0.2)+
  theme_bw(base_size = 14)

ggplot()+
  geom_point(aes(x=pred5$Temperature, y=pred5$dif), alpha=0.1)+
  geom_smooth(aes(x=pred5$Temperature, y=pred5$dif))

  
ggplot()+
  geom_point(aes(x=pred5$Temperature, y=-pred5$EL50+pred5$Damy), alpha=0.2)+
  geom_smooth(aes(x=pred5$Temperature, y=-pred5$EL50+pred5$Damy))+
  theme_bw()

ggplot()+
  geom_col(aes(x=pred5$Temperature,y=(-pred5$EL50+pred5$Damy), group=pred5$Accession),position = "identity", alpha=0.1)+
  geom_smooth(aes(x=pred5$Temperature, y=(-pred5$EL50+pred5$Damy)))+
  scale_x_continuous(limits=c(0,100),breaks=c(0,10,20,30,40,50,60,70,80,90,100))+
  xlab("% Visual damage")+ylab("Prediction difference from 50% Leakage (°C)")+
  theme_bw(base_size = 20)+
  theme(panel.grid.minor=element_blank())



pred3$Accession=factor(pred3$Accession, levels=c("379-2007 A","699-89 A","172-2001 B","435-84 A","435-84 B","435-84 C",
                                                 "666-94 A","122-2003 B","126-2003 B","31-73 A","31-73 B","31-73 C",
                                                 "Bussey1","Bussey2","Bussey3","Weld1","Weld2","Weld3","750-55 B","22858 B",
                                                 "19634 A","524-2009 A","567-2008 B","207-2005 A","530-2008 A","187-2006 B",
                                                 "246-2010 A","124-2005 C","603-2008 A","270-2010 A","1115-76 A","115-2000 A",
                                                 "78-2000 B","33-95 B","1400-77 E","531-94 A"))




###### Plotting both electrolyte leakage and damage curves together, per genotype #####


p=ggplot()+
  geom_line(aes(x=-x+10,y=y),data=pred3)+
  geom_line(aes(x=-x+10,y=y2), lty=2,data=pred3)+
  xlab("Temperature")+
  ylab("Relative damage")+
  #geom_point(aes(y=Temperature,x=dif),size=0.01, data=pred5)+
  theme_bw(base_size = 8)+
  theme(strip.text = element_text(size = 8, color = "black", face = "bold"))+
  facet_wrap(~Accession)

p

#### Can be used to color background per Species ####

g <- ggplot_gtable(ggplot_build(p))
strip_t <- which(grepl('strip-t', g$layout$name))
fills <- c("dark green","dark green","dark green","purple3","purple3","purple3",
           "navyblue","navyblue","navyblue","green4","green4","green4",
           "magenta1","magenta1","magenta1","chartreuse","chartreuse","chartreuse",
           "yellow","yellow","yellow","firebrick1","firebrick1","firebrick1",
           "firebrick4","firebrick4","firebrick4","deeppink","deeppink","deeppink",
           "cyan","cyan","cyan","blue","blue","blue")
k <- 1
for (i in strip_t) {
  j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
  g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}
grid.draw(g)


pred5$Accession=factor(pred5$Accession, levels=c("379-2007 A","699-89 A","172-2001 B","435-84 A","435-84 B","435-84 C",
                                                 "666-94 A","122-2003 B","126-2003 B","31-73 A","31-73 B","31-73 C",
                                                 "Bussey1","Bussey2","Bussey3","Weld1","Weld2","Weld3","750-55 B","22858 B",
                                                 "19634 A","524-2009 A","567-2008 B","207-2005 A","530-2008 A","187-2006 B",
                                                 "246-2010 A","124-2005 C","603-2008 A","270-2010 A","1115-76 A","115-2000 A",
                                                 "78-2000 B","33-95 B","1400-77 E","531-94 A"))


###### This plot shows the differences between the leakage model and Damage #####

p=ggplot()+
  geom_point(aes(y=Temperature,x=dif),data=pred5)+
  theme_bw()+
  facet_wrap(~Accession)

p

#### Can be used to color background per Species ####


g <- ggplot_gtable(ggplot_build(p))
strip_t <- which(grepl('strip-t', g$layout$name))
fills <- c("dark green","dark green","dark green","purple3","purple3","purple3",
           "navyblue","navyblue","navyblue","green4","green4","green4",
           "magenta1","magenta1","magenta1","chartreuse","chartreuse","chartreuse",
           "yellow","yellow","yellow","firebrick1","firebrick1","firebrick1",
           "firebrick4","firebrick4","firebrick4","deeppink","deeppink","deeppink",
           "cyan","cyan","cyan","blue","blue","blue")
k <- 1
for (i in strip_t) {
  j <- which(grepl('rect', g$grobs[[i]]$grobs[[1]]$childrenOrder))
  g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  k <- k+1
}
grid.draw(g)




##### Quantifying the comparison between Damage and Relative Leakage #####

dat=read.csv("MapleStemDamage200324.csv")
cl.dat=read.csv("SpeciesGenos.csv")
dat$posT=-dat$Temperature+10


mod1=drm(dat$Damage~dat$posT, dat$Genotype,fct=LL.2(), type="continuous"   )
summary(mod1)


dat6=read.csv("ResultsbyAccession-L_boiling.csv")
dat6=dat6[,c(3,4,7,8,9)]
colnames(dat6)=c("Genotype","Species","_20_EL_L","_50_EL_L","_80_EL_L")

dat2=data.frame(-ED(mod1,10, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("ten","Genotype")
dat2$Genotype=as.factor(gsub(':10','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat2,cl.dat)


dat2=data.frame(-ED(mod1,20, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("twenty","Genotype")
dat2$Genotype=as.factor(gsub(':20','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)

dat2=data.frame(-ED(mod1,30, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("thirty","Genotype")
dat2$Genotype=as.factor(gsub(':30','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)


dat2=data.frame(-ED(mod1,40, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("forty","Genotype")
dat2$Genotype=as.factor(gsub(':40','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,50, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("fifty","Genotype")
dat2$Genotype=as.factor(gsub(':50','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,60, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("sixty","Genotype")
dat2$Genotype=as.factor(gsub(':60','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,70, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("seventy","Genotype")
dat2$Genotype=as.factor(gsub(':70','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,80, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("eighty","Genotype")
dat2$Genotype=as.factor(gsub(':80','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,90, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("ninety","Genotype")
dat2$Genotype=as.factor(gsub(':90','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)




dat9b=merge(dat6,dat3)
dat9b$Species=as.factor(dat9b$Species)
dat9b$Genotype=as.factor(dat9b$Genotype)


res=cor(dat9b[3:5],dat9b[6:14])



library(corrplot)
corrplot(res, method="pie",cl.lim=c(-1,1), is.corr=T,
         tl.col = "black", tl.srt = 45)



dat10=aggregate(.~Species,dat9b,mean)
dat10b=aggregate(.~Species,dat9b,sd)


dat10=data.frame(dat10[c(1,4)],stack(dat10[6:14]))
dat10b=data.frame(dat10b[c(1,4)],stack(dat10b[6:14]))

colnames(dat10)=c("Species","EL_Relative50","CH_Damage","Percent")
colnames(dat10b)=c("Species","EL_error","CH_error","Percent")

dat10=merge(dat10,dat10b)
dat10$CHoutofrange=NA
dat10$CHoutofrange[dat10$CH_Damage<(-45)]=-44.5


dat10b=data.frame(levels(dat10$Species))
colnames(dat10b)="Species"
dat10b$x=-45
dat10b$y=-45

dat10c=data.frame(levels(dat10$Species))
colnames(dat10c)="Species"
dat10c$x=-5
dat10c$y=-5

dat10b=rbind(dat10b,dat10c)

dat10=merge(dat10,dat10b)


ggplot(data=dat10)+
  geom_smooth(aes(x=EL_Relative50,y=CH_Damage), formula=y~x+0,col="black",size=0.5, method="glm")+
  geom_line(aes(x=x,y=y), lty=2)+
  geom_errorbar(aes(ymin=CH_Damage-CH_error, ymax=CH_Damage, x=EL_Relative50),width=0, col="gray40", size=0.5)+
  geom_errorbar(aes(ymin=CH_Damage, ymax=CH_Damage+CH_error, x=EL_Relative50),width=0, col="gray40",size=0.5)+
  geom_errorbarh(aes(xmin=EL_Relative50-EL_error, xmax=EL_Relative50+EL_error, y=CH_Damage),height=0, col="gray40",size=0.5)+
  geom_point(aes(x=EL_Relative50,y=CH_Damage, col=Species))+
  #geom_point(aes(x=EL_Relative50,y=CHoutofrange, col=Species), stroke=1, shape=25)+
  scale_color_manual(values=c("dark green","purple3","navyblue","green4","magenta1",
                              "chartreuse","yellow","firebrick1","firebrick4","deeppink","cyan","blue"))+
  scale_y_continuous(limits=c(-60,-5), expand=c(0.01,0.01))+
  scale_x_continuous(limits=c(-45,-5), expand=c(0.01,0.01))+
  xlab("T50")+ylab("Damage Assay")+
  theme_bw()+
  facet_wrap(~dat10$Percent)+
  theme(text=element_text(face="bold", color="black"),
        axis.text = element_text(face="bold", color="black"),
        legend.direction = 'vertical', 
        legend.position = c(2,2),
        legend.key.size = unit(1.5, 'lines'),
        legend.text.align= 1,
        legend.title = element_blank(),
        legend.box='horizontal',
        panel.grid.minor =element_blank(),
        panel.grid.major = element_blank(),
        legend.background = element_rect(fill="transparent"),
        legend.key = element_rect( fill = NA))



# Looking at stats for each model from 10 to 90% of the Damage assay #

rmse=sqrt(sum((dat9b[,4]-dat9b[,6])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,6]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,6])
r2=    cor(dat9b[,4],dat9b[,6], method="spearman")

rmse
bias
r
r2

rmse=sqrt(sum((dat9b[,4]-dat9b[,7])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,7]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,7])
r2=    cor(dat9b[,4],dat9b[,7], method="spearman")

rmse
bias
r
r2


rmse=sqrt(sum((dat9b[,4]-dat9b[,8])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,8]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,8])
r2=    cor(dat9b[,4],dat9b[,8], method="spearman")

rmse
bias
r
r2


rmse=sqrt(sum((dat9b[,4]-dat9b[,9])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,9]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,9])
r2=    cor(dat9b[,4],dat9b[,9], method="spearman")

rmse
bias
r
r2


rmse=sqrt(sum((dat9b[,4]-dat9b[,10])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,10]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,10])
r2=    cor(dat9b[,4],dat9b[,10], method="spearman")

rmse
bias
r
r2


rmse=sqrt(sum((dat9b[,4]-dat9b[,11])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,11]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,11])
r2=    cor(dat9b[,4],dat9b[,11], method="spearman")

rmse
bias
r
r2


rmse=sqrt(sum((dat9b[,4]-dat9b[,12])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,12]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,12])
r2=    cor(dat9b[,4],dat9b[,12], method="spearman")

rmse
bias
r
r2


rmse=sqrt(sum((dat9b[,4]-dat9b[,13])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,13]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,13])
r2=    cor(dat9b[,4],dat9b[,13], method="spearman")

rmse
bias
r
r2


rmse=sqrt(sum((dat9b[,4]-dat9b[,14])^2)/nrow(dat9b))
bias=sum((dat9b[,4]-dat9b[,14]))/nrow(dat9b)
r=    cor(dat9b[,4],dat9b[,14])
r2=    cor(dat9b[,4],dat9b[,14], method="spearman")

rmse
bias
r
r2

dat10=aggregate(.~Species,dat9b,mean)

lm1=lm(dat10$forty~0+dat10$`_50_EL_L`)
summary(lm1)

```


```{r}
dat=read.csv("MapleStemDamage200324.csv")
dat$Species=as.factor(dat$Species)
dat$Genotype=as.factor(dat$Genotype)
cl.dat=read.csv("SpeciesGenos.csv")
cl.dat$Species=as.factor(cl.dat$Species)
cl.dat$Genotype=as.factor(cl.dat$Genotype)

dat$posT=-dat$Temperature+10


mod1=drm(dat$Damage~dat$posT, dat$Genotype,fct=LL.2(), type="continuous"   )
summary(mod1)


dat2=data.frame(-ED(mod1,10, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("ten","Genotype")
dat2$Genotype=as.factor(gsub(':10','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat2,cl.dat)


dat2=data.frame(-ED(mod1,20, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("twenty","Genotype")
dat2$Genotype=as.factor(gsub(':20','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)

dat2=data.frame(-ED(mod1,30, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("thirty","Genotype")
dat2$Genotype=as.factor(gsub(':30','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)


dat2=data.frame(-ED(mod1,40, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("forty","Genotype")
dat2$Genotype=as.factor(gsub(':40','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,50, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("fifty","Genotype")
dat2$Genotype=as.factor(gsub(':50','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,60, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("sixty","Genotype")
dat2$Genotype=as.factor(gsub(':60','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,70, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("seventy","Genotype")
dat2$Genotype=as.factor(gsub(':70','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,80, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("eighty","Genotype")
dat2$Genotype=as.factor(gsub(':80','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,90, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("ninety","Genotype")
dat2$Genotype=as.factor(gsub(':90','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)








dat=read.csv("ELMethodOut3.csv")
dat$Species=as.factor(dat$Species)

tdat=read.csv("ELTemp.csv")
tdat=aggregate(ActualT~Collection+Temperature,tdat,mean)
colnames(tdat)=c("Date","Temperature","RealT")
dat=merge(dat,tdat, by=c("Date","Temperature"))



dat1=subset(dat, Date %in% "3/13/20")
summary(dat1)

dat1$wrong=0
dat1$wrong[dat1$Cond_freeze>1.3*dat1$Cond_N]=1

dat1=subset(dat1, wrong %in% 0)
summary(dat1)


dat1$Cond_boiling[is.na(dat1$Cond_boiling)]=dat1$Cond_N[is.na(dat1$Cond_boiling)]/0.5758


dat1$Rt=dat1$Cond_freeze/dat1$Cond_boiling
dat1=dat1[complete.cases(dat1),]


lm1=lm(dat1$Rt~dat1$Accession+as.factor(dat1$RealT))
Anova(lm1)


stud.res=studres(lm1)
plot(lm1$fitted.values,stud.res)
abline(0,0)
abline(3,0)
plot(dat1$Rt,stud.res)
hist(stud.res,breaks=50)
qqPlot(stud.res)
cooks.dist=cooks.distance(lm1)
plot(cooks.dist)



not_outlier = which(abs(stud.res) <= 4)
dat1=dat1[not_outlier,]



#### Step to normalize 4C as 0 ####

dat2=subset(dat1, RealT %in% 4)
dat2$Ro=dat2$Cond_freeze/dat2$Cond_boiling
dat2=aggregate(Ro~Accession,dat2,mean)
dat1=merge(dat1,dat2, by="Accession")


#### Step to take maximum average leakage ####

dat2=dat1
dat2=aggregate(Rt~Accession+RealT,dat2,mean)
dat2=aggregate(Rt~Accession,dat2,max)
colnames(dat2)=c("Accession","Rmax")
dat1=merge(dat1,dat2,by="Accession")

#### Normalizing from 0 to 100 ####

dat1$L=100*(dat1$Rt-dat1$Ro)/(dat1$Rmax-dat1$Ro)



#### Create positive-only temperatures ####

dat1$posRT=-dat1$RealT
dat1$posRT=dat1$posRT+10



library(drc)
mod1=drm((dat1$L/100)~dat1$posRT,dat1$Accession, fct=LL.2() , type="continuous" )
summary(mod1)




dat2=data.frame(-ED(mod1,10, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("tenEL","Genotype")
dat2$Genotype=as.factor(gsub(':10','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)


dat2=data.frame(-ED(mod1,20, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("twentyEL","Genotype")
dat2$Genotype=as.factor(gsub(':20','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)

dat2=data.frame(-ED(mod1,30, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("thirtyEL","Genotype")
dat2$Genotype=as.factor(gsub(':30','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)


dat2=data.frame(-ED(mod1,40, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("fortyEL","Genotype")
dat2$Genotype=as.factor(gsub(':40','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,50, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("fiftyEL","Genotype")
dat2$Genotype=as.factor(gsub(':50','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,60, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("sixtyEL","Genotype")
dat2$Genotype=as.factor(gsub(':60','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,70, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("seventyEL","Genotype")
dat2$Genotype=as.factor(gsub(':70','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,80, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("eightyEL","Genotype")
dat2$Genotype=as.factor(gsub(':80','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)
dat2=data.frame(-ED(mod1,90, interval="delta", type="relative", level=0.95)[,1])+10

dat2$Genotypes=rownames(dat2)
colnames(dat2)=c("ninetyEL","Genotype")
dat2$Genotype=as.factor(gsub(':90','',gsub('e:','',dat2$Genotype)))

dat3=merge(dat3,dat2)



res=cor(dat3[20:12],dat3[c(2,4:11)])


rownames(res)=c("90_EL","80_EL","70_EL","60_EL","50_EL","40_EL","30_EL","20_EL","10_EL")
colnames(res)=c("10_Visual","20_Visual","30_Visual","40_Visual","50_Visual","60_Visual","70_Visual","80_Visual","90_Visual")


library(corrplot)
corrplot(res, method="color",cl.lim=c(0,0.7), is.corr=F,
         tl.col = "black", tl.srt = 45)


dat4=dat3[c(2,4:11)]
dat5=dat3[20:12]


mat.test=matrix(data=NA, nrow=9, ncol=9)

for (i in 1:9) {
  
  for (j in 1:9) {
    
    rmse=sqrt(sum((dat4[i]-dat5[j])^2)/nrow(dat4))
    mat.test[i,j]=rmse
    
  }
  
}

rownames(mat.test)=c("90_EL","80_EL","70_EL","60_EL","50_EL","40_EL","30_EL","20_EL","10_EL")
colnames(mat.test)=c("10_Visual","20_Visual","30_Visual","40_Visual","50_Visual","60_Visual","70_Visual","80_Visual","90_Visual")


mat.testb=log(mat.test,2)
corrplot(mat.testb, method="color",cl.lim=c(2,5.5), is.corr=F,
         tl.col = "black", tl.srt = 45)


mat.test2=matrix(data=NA, nrow=9, ncol=9)


for (i in 1:9) {
  
  for (j in 1:9) {
    
    bias=sum((dat4[i]-dat5[j]))/nrow(dat4)
    mat.test2[i,j]=bias
    
  }
  
}


rownames(mat.test2)=c("90_EL","80_EL","70_EL","60_EL","50_EL","40_EL","30_EL","20_EL","10_EL")
colnames(mat.test2)=c("10_Visual","20_Visual","30_Visual","40_Visual","50_Visual","60_Visual","70_Visual","80_Visual","90_Visual")


corrplot(mat.test2, method="color",cl.lim=c(-35,35), is.corr=F,
         tl.col = "black", tl.srt = 45)




mat.test3=matrix(data=NA, nrow=9, ncol=9)

dat3alt=dat3[,c(1,3,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)]

for (i in 1:9) {
  
  for (j in 1:9) {
    
    ii=2+i
    jj=11+j
    lm5=lmer(dat3alt[,ii]~dat3alt[,jj]+(1|dat3alt$Species))
    summary(lm5)
    pv=as.numeric(Anova(lm5)[3])
    mat.test3[(10-i),(10-j)]=pv
    
  }
  
}


rownames(mat.test3)=c("90_EL","80_EL","70_EL","60_EL","50_EL","40_EL","30_EL","20_EL","10_EL")
colnames(mat.test3)=c("10_Visual","20_Visual","30_Visual","40_Visual","50_Visual","60_Visual","70_Visual","80_Visual","90_Visual")

mat.test3b=log(mat.test3)

corrplot((mat.test3b), method="color", is.corr=F,
         tl.col = "black", tl.srt = 45)




#### Comparing with DTA data ####

dta=read.csv("MapleStemDTACombined.csv")
dta$LTE=-dta$LTE
dta=subset(dta, Date %in% "3/17/20")


dta=merge(dta,dat3, all=T)
dta=dta[complete.cases(dta),]

lm5=lm(LTE~fiftyEL, data=dta)
summary(lm5)
Anova(lm5)

cor(dta$LTE,dta$fiftyEL)
cor(dta$LTE,dta$fiftyEL, method="spearman")

plot(dta$LTE,dta$fiftyEL)


library(lme4)


lm5=lmer(LTE~fiftyEL+(1|Species), data=dta)
summary(lm5)
Anova(lm5)


lm5=lmer(LTE~fifty+(1|Species), data=dta)
summary(lm5)
Anova(lm5)

cor(dta$LTE,dta$fifty)

```

